# Generated by Django 5.2.14 on 2026-05-14 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_az', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (AZ)')),
                ('main_title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (EN)')),
                ('main_title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (RU)')),
                ('second_title_az', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (AZ)')),
                ('second_title_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (EN)')),
                ('second_title_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (AZ)')),
                ('description_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (EN)')),
                ('description_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (RU)')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='AppealContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Mövzu')),
                ('info', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Əlaqə müraciəti',
                'verbose_name_plural': 'Əlaqə müraciətləri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=255, verbose_name='Başlıq (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq (RU)')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Şəkil')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (RU)')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Baxış sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_az', models.CharField(max_length=255, verbose_name='Ünvan (AZ)')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (RU)')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_two', models.EmailField(blank=True, max_length=254, null=True, verbose_name='İkinci email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedn', models.URLField(blank=True, null=True, verbose_name='Linkedn')),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqələr',
            },
        ),
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(AZ)')),
                ('text_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(EN)')),
                ('text_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(RU)')),
            ],
            options={
                'verbose_name': 'Deviz',
                'verbose_name_plural': 'Deviz',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (RU)')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedn', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Məhsul adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Məhsul adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Məhsul adı (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Məhsul haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Məhsul haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Məhsul haqqında (RU)')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Məhsul aktivliyi')),
                ('on_main_page', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ana səhifədə olsun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (RU)')),
            ],
            options={
                'verbose_name': 'Kateqoriya adı',
                'verbose_name_plural': 'Kateqoriya adları',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_one', models.PositiveIntegerField(verbose_name='Dəyər sayı 1')),
                ('value_two', models.PositiveIntegerField(verbose_name='Dəyər sayı 2')),
                ('value_three', models.PositiveIntegerField(verbose_name='Dəyər sayı 3')),
                ('value_four', models.PositiveIntegerField(verbose_name='Dəyər sayı 4')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('is_home_page_background_image', models.BooleanField(default=False, verbose_name='Ana səhifə fon şəkli')),
                ('is_about_page_background_image', models.BooleanField(default=False, verbose_name='Haqqımızda səhifəsi fon şəkli')),
                ('is_contact_page_background_image', models.BooleanField(default=False, verbose_name='Əlaqə səhifəsi fon şəkli')),
                ('is_product_page_background_image', models.BooleanField(default=False, verbose_name='Məhsullar səhifəsi fon şəkli')),
                ('is_footer_background_image', models.BooleanField(default=False, verbose_name='Footer fon şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.about', verbose_name='Haqqımızda')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.partner', verbose_name='Tərəfdaş')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='projects.productcategory', verbose_name='Kateqoriya'),
        ),
    ]
