# Generated by Django 5.2.14 on 2026-05-16 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_blog_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motto',
            name='text_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(EN)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_az',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Məhsul haqqında (AZ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Məhsul haqqında (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Məhsul haqqında (RU)'),
        ),
    ]
