# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_media_multilingual_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_blog_page_background_image',
            field=models.BooleanField(
                default=False,
                verbose_name='Bloq səhifələri fon şəkli',
            ),
        ),
    ]
