# Generated by Django 6.0.4 on 2026-05-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_media_blog_page_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Səhifə fon şəkli', 'verbose_name_plural': 'Səhifə fon şəkilləri'},
        ),
    ]
