# Generated by Django 5.2.14 on 2026-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_statistic_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 4 — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 4 — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 4 — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 1 — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 1 — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 1 — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 3 — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 3 — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 3 — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 2 — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 2 — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Say 2 — alt yazı (RU)'),
        ),
    ]
