# Generated by Django 5.2.14 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_statistic_caption_four_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_az', models.CharField(max_length=500, verbose_name='Sual (AZ)')),
                ('question_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sual (EN)')),
                ('question_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sual (RU)')),
                ('answer_az', models.TextField(verbose_name='Cavab (AZ)')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Cavab (EN)')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Cavab (RU)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Kiçik rəqəm yuxarıda göstərilir.', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
