# Generated by Django 5.2.14 on 2026-05-21 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_media_faq_page_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda səhifəsi', 'verbose_name_plural': 'Haqqımızda səhifəsi'},
        ),
        migrations.AlterModelOptions(
            name='appealcontact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gələn mesaj (əlaqə forması)', 'verbose_name_plural': 'Gələn mesajlar (əlaqə forması)'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Bloq yazısı', 'verbose_name_plural': 'Bloq yazıları'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə məlumatları', 'verbose_name_plural': 'Əlaqə məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Tez-tez verilən sual', 'verbose_name_plural': 'Tez-tez verilən suallar'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Səhifə banner fon şəkli', 'verbose_name_plural': 'Səhifə banner fon şəkilləri'},
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name': 'Deviz (slogan)', 'verbose_name_plural': 'Devizlər (sloganlar)'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Məhsul kateqoriyası', 'verbose_name_plural': 'Məhsul kateqoriyaları'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistika (saylar bloku)', 'verbose_name_plural': 'Statistika (saylar bloku)'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description_az',
            field=models.TextField(help_text='Şirkət haqqında əsas mətn — Haqqımızda səhifəsində və ana səhifədə qısa blokda.', validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (AZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (EN)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ru',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (RU)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_title_az',
            field=models.CharField(blank=True, help_text='Haqqımızda səhifəsində böyük başlıq.', max_length=120, null=True, verbose_name='Əsas başlıq (AZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, help_text='Haqqımızda və ana səhifədə göstərilən yeganə video. Yalnız bir fayl yükləyin.', null=True, upload_to='videos/about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='Allowed formats: mp4, webm, mov, ogg, mkv.')], verbose_name='Əsas tanıtım videosu'),
        ),
        migrations.AlterField(
            model_name='about',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Video oynatılmadan əvvəl görünən şəkil.', null=True, upload_to='images/about/video_posters/', verbose_name='Video örtüyü (poster)'),
        ),
        migrations.AlterField(
            model_name='appealcontact',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mesajı oxuduqdan sonra işarələyin.', verbose_name='Oxunub?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='on_main_page',
            field=models.BooleanField(default=False, help_text='Ana səhifədə ən çox 6 bloq yazısı göstərilir.', verbose_name='Ana səhifədə göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Avtomatik sayılır — dəyişdirməyin.', verbose_name='Baxış sayı'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps-dən «Paylaş → Xəritəni daxil et» bölməsindən iframe src linkini yapışdırın.', null=True, verbose_name='Google Xəritə linki (embed)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Saytda göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Kiçik rəqəm = siyahıda yuxarıda. Məs: 1, 2, 3...', verbose_name='Sıra nömrəsi'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='is_about_page',
            field=models.BooleanField(default=False, help_text='Haqqımızda səhifəsinin yuxarı fon şəklinin üstündə.', verbose_name='Haqqımızda səhifəsinin banneri'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='is_blog_page',
            field=models.BooleanField(default=False, verbose_name='Bloq səhifəsinin banneri'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='is_contact_page',
            field=models.BooleanField(default=False, verbose_name='Əlaqə səhifəsinin banneri'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='is_product_page',
            field=models.BooleanField(default=False, verbose_name='Məhsullar səhifəsinin banneri'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='show_on_home_hero',
            field=models.BooleanField(default=True, help_text='Ana səhifənin yuxarı böyük şəkil slayderində bu deviz görünür.', verbose_name='Ana səhifə karuselində göstər?'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_az',
            field=models.TextField(help_text='Ana səhifə karuseli və ya səhifə bannerində görünən qısa cümlə.', validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (AZ)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (EN)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (RU)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Söndürsəniz tərəfdaş karuseldə görünməz.', verbose_name='Saytda göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Söndürsəniz məhsul saytda görünməz.', null=True, verbose_name='Saytda göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_main_page',
            field=models.BooleanField(blank=True, default=False, help_text='Hər kateqoriyada ana səhifədə ən çox 6 məhsul ola bilər.', null=True, verbose_name='Ana səhifədə göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_az',
            field=models.CharField(blank=True, help_text='Məs: Layihə sayı', max_length=255, verbose_name='4-cü kart — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='4-cü kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='4-cü kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_az',
            field=models.CharField(blank=True, help_text='Rəqəmin altında görünən qısa mətn. Məs: İllik təcrübə', max_length=255, verbose_name='1-ci kart — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_en',
            field=models.CharField(blank=True, help_text='English version of the caption below the first number.', max_length=255, verbose_name='1-ci kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_ru',
            field=models.CharField(blank=True, help_text='Русская версия подписи под первым числом.', max_length=255, verbose_name='1-ci kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_az',
            field=models.CharField(blank=True, help_text='Məs: Müştəri sayı', max_length=255, verbose_name='3-cü kart — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='3-cü kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='3-cü kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_az',
            field=models.CharField(blank=True, help_text='Məs: Məhsul növü', max_length=255, verbose_name='2-ci kart — alt yazı (AZ)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='2-ci kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='2-ci kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_four',
            field=models.PositiveIntegerField(help_text='Məsələn: 1000. Dördüncü statistika kartındakı rəqəm.', verbose_name='4-cü kart — böyük rəqəm'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_one',
            field=models.PositiveIntegerField(help_text='Məsələn: 25. Ana səhifə və Haqqımızda səhifəsində sol tərəfdəki birinci rəqəm.', verbose_name='1-ci kart — böyük rəqəm'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_three',
            field=models.PositiveIntegerField(help_text='Məsələn: 500. Üçüncü statistika kartındakı rəqəm.', verbose_name='3-cü kart — böyük rəqəm'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_two',
            field=models.PositiveIntegerField(help_text='Məsələn: 150. İkinci statistika kartındakı rəqəm.', verbose_name='2-ci kart — böyük rəqəm'),
        ),
    ]
