# Generated by Django 6.0.4 on 2026-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_appealcontact_subject_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
