# Generated by Django 6.0.4 on 2026-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_appealcontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealcontact',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Mobil nömrə'),
        ),
    ]
